### ISSUE TITLE
unable to receive message from FDR

### ISSUE THREAD

**Issue by ZASAonSK** [CoocooFroggy/FutureRestore-GUI#102]
https://preview.redd.it/19cx75q69sn91.png?width=1920&format=png&auto=webp&s=805edd7ffbb5fd651861333008a0e6c1ca8244de

**Comment by Nazky** [comment]
you need to force 15.6.1 (or 15.7)

(in option -> custom latest)

**Comment by CoocooFroggy** [comment]
Yes, don't use Latest SEP and Baseband at that will use 16.0's SEP and Baseband.

**Comment by ZASAonSK** [comment]
Yes I figured that out but thanks anyway 😅
