### ISSUE TITLE
Crashes on Monterey. Java issue?

### ISSUE THREAD

**Issue by FreQRiDeR** [CoocooFroggy/FutureRestore-GUI#108]
Latest crashes on Monterey. Appears to be a Java issue? Any fix suggestions? I have java installed via Home-brew / Temurin.

[hs_err_pid1197.log](https://github.com/CoocooFroggy/FutureRestore-GUI/files/9758845/hs_err_pid1197.log)

**Comment by FreQRiDeR** [comment]
I did that, actually. Same results. Java is a bit wonky these days on modern MacOS. Will try resolving java issue somehow.

**Comment by FreQRiDeR** [comment]
Actually, I get this error when running GUI from command line... I tried several JRE versions from 8 to 19. Same results.

terramoda@Mac-DaDDY ~ % sudo /Applications/FutureRestore\ GUI.app/Contents/MacOS/FutureRestore\ GUI
Password:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000137bba0ec, pid=2453, tid=80903
#
# JRE version: OpenJDK Runtime Environment Temurin-18.0.2.1+1 (18.0.2.1+1) (build 18.0.2.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (18.0.2.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AMDRadeonX4000GLDriver+0x290ec]  glrATIVertexFetchDetermineFetchOrder+0x11e
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

**Comment by FreQRiDeR** [comment]
`Last` login: Wed Oct 12 21:46:52 on ttys000
terramoda@Mac-DaDDY ~ % java --version
openjdk 18.0.2.1 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
terramoda@Mac-DaDDY ~ %

**Comment by FreQRiDeR** [comment]
Solved! Pyenv was configured improperly. Changing global python to 3.10 fixed issue. Closing.

**Comment by CoocooFroggy** [comment]
Not even sure how that solved it since FRGUI doesn't use python 😅
Glad it's working though.

**Comment by FreQRiDeR** [comment]
Well I thought it did then I reinstalled Temurin JRE 19 and now it crashes again. Even removing the Java VM didn't help and crashing persists. It also wreaked havoc on several Homebrew packages that use ptyhon3. I hate Java. Lol!

**Comment by CoocooFroggy** [comment]
@FreQRiDeR can you try this build? It uses Java 19 now instead of 18. You still shouldn't have to install anything since it's bundled.
https://github.com/CoocooFroggy/FutureRestore-GUI/actions/runs/3260751372

**Comment by FreQRiDeR** [comment]
Check your Zip, DMG file. I downloaded it twice but couldn't unarchive with several unarchivers. Kick, BZip etc...

**Comment by CoocooFroggy** [comment]
Aren't you on macOS? It should work with the default Archive Utility. It's just a zip with the DMG inside

**Comment by FreQRiDeR** [comment]
Yes Monterey. Wouldn't unzip. Check it.

**Comment by FreQRiDeR** [comment]
It worked after I redownloaded it without VPN. Sorry my computer is not cooperating! There is a conflict somewhere as many CL apps are not functioning and throwing an "illegal hardware instruction" error. Not an issue w FR-Gui.

**Comment by CoocooFroggy** [comment]
To confirm, the app runs and isn't crashing anymore?
