### ISSUE TITLE
Device ApNonce does not match APTicket nonce

### ISSUE THREAD

**Issue by emnyaz** [CoocooFroggy/FutureRestore-GUI#117]
![c6456331895c716c5676a5ea5dfde8c](https://user-images.githubusercontent.com/73676693/202919684-14a01a95-199f-41c0-abad-4f725f279122.jpg)

什么意思

**Comment by emnyaz** [comment]
![492f5b6278208675b5d15819a668972](https://user-images.githubusercontent.com/73676693/202919829-23d5db88-6a4e-4107-9590-76dcf081a195.jpg)
值一样

**Comment by emnyaz** [comment]
a12  15.0 降级14.5 失败

**Comment by CoocooFroggy** [comment]
This is your device's "generator" -> "AP nonce":

`0xBBACD6DAA24985F7` -> `123b2c053074b3393dadf97c09469086fd5fc2f984dd56444e22e217cf515e12`

You need to find the "generator" that will create the "AP Nonce" in your ".shsh2 blob". 

`0x????????????????` -> `Blob AP nonce`
