### ISSUE TITLE
Error? SLF4J: Failed to load class?

### ISSUE THREAD

**Issue by ss1777** [CoocooFroggy/FutureRestore-GUI#123]
Futurerestore gui Error?

Anyone seen this error before and how to resolve?
 -On win10 using futurerestore 1.98.3v
-IPhone 10,6 13.3 to 15.6rc
-iPhone jailbroken with same generator in blob
-tried diff computer

I’m stuck
Thanks

“SLF4J: Failed to load class “org.slf4j.impl.staticLaggerBinder” It just shows this error when pressing start FutureRestore and opens a new window with this showing on the old one. No actual execution happens.

**Comment by CoocooFroggy** [comment]
You selected FutureRestore-**GUI** as the executable for FutureRestore. You need to either download FutureRestore with the button or select one manually.

I think this is the latest Windows version at the time of writing.

https://cdn.cryptiiiic.com/bin/Windows/x86_64/futurerestore/futurerestore-Windows-x86_64-v2.0.0-test-Build_304-RELEASE.exe

**Comment by ss1777** [comment]
Ah that makes sense. I though future restore was part of this gui but it’s a bridge to grab all the files needed. Awesome thanks for clarification.
