### ISSUE TITLE
Not working Windows 10 "SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by alan0048** [CoocooFroggy/FutureRestore-GUI#124]
Blob file created through blobsaver [github.com/airsquared)
Signed ipsw file downloaded (google)

Problem: GUI does not work

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Checking for FutureRestore GUI updates in the background...
Newest FRGUI version: v1.98.3
You're on the latest version of FutureRestore GUI.

What is the problem? And more importantly, how does one fix it? 
I've read the slf4j homepage, it did not help at all.

System: Windows 10 Pro 64-bit 
Program: FutureRestore-GUI-Windows-1.98.3.msi

**Comment by alan0048** [comment]
Any chance you can upgrade the program and release a new version where it's fixed?

**Comment by CoocooFroggy** [comment]
See #123
