### ISSUE TITLE
why my shsh2 file is  bshsh2 file

### ISSUE THREAD

**Issue by chenfanfang** [CoocooFroggy/FutureRestore-GUI#129]
<img width="819" alt="image" src="https://github.com/CoocooFroggy/FutureRestore-GUI/assets/13808962/839176d9-0d0e-4c2d-8a12-54b373a3d2a7">

<img width="1054" alt="image" src="https://github.com/CoocooFroggy/FutureRestore-GUI/assets/13808962/1ffe8295-511c-4dcf-982f-08696ed98ffc">

what can i do ?

thanks

**Comment by CoocooFroggy** [comment]
You can rename from `bshsh2` to regular `shsh2` to use it, but I'm not sure if it would actually work. I have not heard of bshsh2. My best guess is that it's a blob for the baseband only, but I'm not sure.

**Comment by Cryptiiiic** [comment]
Just binary plist, shouldn’t affect anything, conan enabled it for space reasons

**Comment by CoocooFroggy** [comment]
Oh that's awesome. I'll add the extension to FRGUI then

@chenfanfan you can probably just rename to shsh2 and it will still work

**Comment by chenfanfang** [comment]
thanks

**Comment by minhdanlc124** [comment]
@chenfanfang how can i use it
