### ISSUE TITLE
Error on Windows 10/11:  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by ysmalik09** [CoocooFroggy/FutureRestore-GUI#131]
Hi, 
I'm getting following error all the time. Reinstalled FR 4 times, after uninstalling itunes and all apple software drivers.
Error Message:
      SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
      SLF4J: Defaulting to no-operation (NOP) logger implementation
       SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details
Got same error even after installing jre-8u371-windows-x64, placing following 3 files in java/lib as well as in FR/lib
slf4j-api-2.0.7.jar, slf4j-simple-2.0.7.jar
slf4j-nop-1.1.0-rc1-sources.jar

**Comment by CoocooFroggy** [comment]
See #123

**Comment by ysmalik09** [comment]
Hi, 
Thanks for your response. However, got following error, which is different that discussed above. My blob is perfectly fine, just downloaded from tss server for ios  16.5. Trying to downgrading from ios 16.5.1 to 16.5. Futurerestore downloaded everything but before restoring it threw following exception. 
[exception]:
what=APTicket can't be used for this restore

code=70647860
line=1078
file=C:/Users/Cryptic/futurerestore/src/futurerestore.cpp
commit count=304:
commit sha  =ca45da2fb075ccf2921bbc04d5aef74e3e71b743:
Done: restoring failed!

**Comment by CoocooFroggy** [comment]
That means the blob you are using is for the wrong type of restore you requested. Either it is for the wrong version, or it could be that the blob does not support `-u` and you are using that, or maybe the blob is an OTA blob and you are not using pwndfu. I think futurerestore will tell you the specifics above that error in the log.
