### ISSUE TITLE
coocoofroggy.me offline

### ISSUE THREAD

**Issue by monsm** [CoocooFroggy/FutureRestore-GUI#135]
coocoofroggy.me offline

**Comment by CoocooFroggy** [comment]
Thank you for pointing this out! I've decided to no longer renew the domain as the maintainers of FutureRestore no longer need to analyze recent logs to solve issues. If you are interested in the statistics of those who opted to share logs:

As of August 21, 2023:

- 778,911 total logs shared
- 16,459 successful restores
- 143,054 presses of the "exit recovery" button

**Comment by monsm** [comment]
The software automatically checked the log share in the first run, could not connect to the log server resulting in connection error and termination, most people should not know what is going on, i was looking at the GitHub source to know that the domain name is to collect logs, after turning off sharing logs software can be used normally, thanks again great work.

**Comment by CoocooFroggy** [comment]
Hm, are you sure it caused the software to crash / terminate? It should show a warning message in the log, but FRGUI should still be able to be used normally.

**Comment by monsm** [comment]
100% interrupt execution

**Comment by CoocooFroggy** [comment]
Strange, I cannot reproduce—it is only a single line warning in the log for me. Additionally, it only attempts to share logs after the program finishes running, so I don't see how it could interrupt execution of FutureRestore. 

If you would like to share a recording of the issue, or if this becomes a commonly reported problem, I can patch out the now obsolete "share log" feature. But thank you for reporting regardless!
