### ISSUE TITLE
FR not launching on Macos

### ISSUE THREAD

**Issue by BK-STAR77** [CoocooFroggy/FutureRestore-GUI#21]
Hello

All the latest version not launching. The last version working v1.60

Os: MacOS BigSur 11.2.3

**Comment by CoocooFroggy** [comment]
Hey there, I am able to reproduce the issue. Will attempt to fix it right now.

**Comment by CoocooFroggy** [comment]
@BK-STAR77 would you mind trying the Mac app uploaded as an asset to [release 1.72](https://github.com/CoocooFroggy/FutureRestore-GUI/releases/tag/1.72)?

**Comment by BK-STAR77** [comment]
> @BK-STAR77 would you mind trying the Mac app uploaded as an asset to [release 1.72](https://github.com/CoocooFroggy/FutureRestore-GUI/releases/tag/1.72)?

Perfect!!! It works now!! thank you
