### ISSUE TITLE
Latest BuildManifest is somehow unknown

### ISSUE THREAD

**Issue by asislife20** [CoocooFroggy/FutureRestore-GUI#36]
iPad 7,11
trying to downgrade from 14.5.1 to 14.3
Everything goes fine untill near the end then it says somthing about the build manifest being unknown.

</dict>
</plist>
NOTE: Unable to find BbChipID node
NOTE: Unable to find BbProvisioningManifestKeyHash node
NOTE: Unable to find BbActivationManifestKeyHash node
NOTE: Unable to find BbCalibrationManifestKeyHash node
NOTE: Unable to find BbFactoryActivationManifestKeyHash node
NOTE: Unable to find BbFDRSecurityKeyHash node
NOTE: Unable to find BbSkeyId node
Sending SE TSS request...
common.c:printing 920 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>@Locality</key>
	<string>en_US</string>
	<key>@HostPlatformInfo</key>
	<string>mac</string>
	<key>@VersionInfo</key>
	<string>libauthinstall-698.0.5</string>
	<key>@UUID</key>
	<string>B886186A-BBC4-8289-A15E-0537D7BDC396</string>
	<key>@BBTicket</key>
	<true/>
	<key>@SE,Ticket</key>
	<true/>
	<key>SE,ChipID</key>
	<integer>100</integer>
	<key>SE,ID</key>
	<data>
	BDwfg6xQgAGQIAYyYJSVOQurj1IaDawJ
	</data>
	<key>SE,Nonce</key>
	<data>
	6TMHldulvCE54Chs2kiQ+GsVMhA=
	</data>
	<key>SE,RootKeyIdentifier</key>
	<data>
	YzErNV1rVT5vssRti6cpWKctuCBprCmvZDv6ysfO+uI=
	</data>
	<key>SE,UpdatePayload</key>
	<dict>
		<key>ProductionUpdatePayloadHash</key>
		<data>
		FvjfWFVdHtV1VO7AQeurSjeUyDjbZojSefdBQ9lZLIs=
		</data>
	</dict>
</dict>
</plist>
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... Warning: Unable to fetch SE ticket using current build_identity, trying again using latest build manifest
ERROR: Unable to fetch Savage ticket because latest build manifest is somehow unkown, this is not normal, RIPERONI :(
ERROR: restore_send_firmware_updater_data: Couldn't get SE firmware data
ERROR: Unable to send FirmwareUpdater data
ERROR: Unable to successfully restore device
FDR 0x7fa7fc775f80 timeout waiting for command
FDR 0x7fa7fc775f80 waiting for message...
FDR 0x7fa7fc775f80 timeout waiting for command
FDR 0x7fa7fc775f80 waiting for message...
No data to read (timeout)
FDR 0x7fa7fc775f80 terminating...
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=68026385
line=1038
file=futurerestore.cpp
commit count=194:
commit sha  =0ab9df3209ee599f581532d05d331e6abe0f53f3:
Done: restoring failed!

**Comment by CoocooFroggy** [comment]
iPad7,11 seems to be a WiFi only iPad. If you can confirm this is true, you should use "No baseband"

**Comment by CoocooFroggy** [comment]
If you're already using no baseband, let me know—there is another case of something similar happening.

**Comment by asislife20** [comment]
It is WiFi only and I am using no baseband command.

**Comment by CoocooFroggy** [comment]
[Here is a build](https://cadoth.net/~nyuszika7h/futurerestore-v205) by @nyuszika7h which should solve the problem. You should use this on Ubuntu, and click "Select FutureRestore binary / executable", choosing this file.

**Comment by tehgunte** [comment]
Sorry to bump this or revive it again but, i cannot seem to find the build you provided anymore as it has been deleted, and the exact version is not listed on nyuszika's fork
I happen to have the exact same problem with the exact same model and device

**Comment by asislife20** [comment]
@tehgunte If your device is wifi only there's a specific build for it, and no others have worked for me. It was somewhat difficult to find, but ended up being like the third line down on the official future restore GitHub. To make it easier for you this is the only build that worked for me. Hope it helps.

https://nightly.link/futurerestore/futurerestore/workflows/ci/main

**Comment by tehgunte** [comment]
@asislife20 Works like a charm!
Thanks a lot!

**Comment by CoocooFroggy** [comment]
@asislife20 by third down the line, did you mean the third link on that page's list at the most recent version (futurerestore-Linux-x86_64-RELEASE)? Or the third most recent build/commit at c15e30b with [iOS 16 support, update submodules](https://github.com/futurerestore/futurerestore/commit/c15e30b290141e47383de93aa6b0273b7b6df8d6)?

**Comment by asislife20** [comment]
@CoocooFroggy I mean on the official future restore github. The third line in the description says wifi only devices need to use that specific build. 
![Screenshot_2022-09-24-20-35-42-305](https://user-images.githubusercontent.com/46206524/192127132-0ea1085e-d6b5-4097-a95f-f3f787ae7080.png)

**Comment by CoocooFroggy** [comment]
That's just the latest beta version. FutureRestore-GUI should automatically download that with the "FutureRestore Beta" option enabled.
