### ISSUE TITLE
“Send log” button once restore goes unsuccessful

### ISSUE THREAD

**Issue by dabezt31** [CoocooFroggy/FutureRestore-GUI#46]
Self explanatory, if the restore fails, then FutureRestore GUI gives an option to user to export the log

**Comment by CoocooFroggy** [comment]
The GUI already saves logs locally automatically to `[home folder]/FutureRestoreGUI/logs/`, and if the Share Logs setting is enabled, it will send the log once the FutureRestore process dies.

I'll consider maybe a notification or a pop-up letting the user know their log was saved or sent.
