### ISSUE TITLE
futurerestore Binary Path is Assumed During Restore Process

### ISSUE THREAD

**Issue by joshuaseltzer** [CoocooFroggy/FutureRestore-GUI#58]
I was attempting to use my own local copy of the `futurerestore` binary instead of the one that the application would download and put in my home directory. Unfortunately it looks like this feature doesn't work. I pointed out the line in your code where the process goes back and assumes that it's still in the home directory (in the `FutureRestoreGUI` folder).

https://github.com/CoocooFroggy/FutureRestore-GUI/blob/37e7e3985fe51844abd2603f5eb60222f4821c6e/src/main/java/FutureRestoreWorker.java#L30

**Comment by CoocooFroggy** [comment]
I am not able to reproduce the issue on macOS Big Sur. What operating system are you using?

The variable you linked is only used to set the working directory of the process. This line is basically used to set the binary's path in the process builder.

https://github.com/CoocooFroggy/FutureRestore-GUI/blob/37e7e3985fe51844abd2603f5eb60222f4821c6e/src/main/java/FutureRestoreWorker.java#L26

**Comment by joshuaseltzer** [comment]
Ah okay, that was just after a very quick glance at the code.  Maybe it's not related to the binary, but the file path itself? If I deleted the `FutureRestoreGUI` folder from my home directory, would that cause the app not to function?

It was hanging on "Starting FutureRestore."  When I had it download the futurerestore binary directory into the home folder, it worked flawlessly!
