### ISSUE TITLE
Futurerestore iPhone 7 to iOS 14.3 fails.

### ISSUE THREAD

**Issue by masckmaster2007** [CoocooFroggy/FutureRestore-GUI#59]
When i try to restore/upgrade my iPhone 7 to iOS 14.3 with blobs, it fails every time at gg.apple.com:443 payload.

After some research, I've found that the Baseband was maybe not compatible with iOS 14.3.

HOWEVER, all of the tries that I've made in the past were before iOS 15 official release, during Augustus to early September.

So, is it now **possible** and **safe** to futurerestore my iPhone 7 to iOS 14.3 with latest baseband and SEP ?

Thanks !

Also, the main reason i want to downgrade is to get the untethered jailbreak.

**Comment by CoocooFroggy** [comment]
You should manually specify iOS 14.8 SEP and Baseband. I believe tsschecker was having issues with iOS 15. Let me know if you need any help.

**Comment by masckmaster2007** [comment]
If i am jailbroken w/ checkra1n, do i check AP Nonce Collision ?

**Comment by CoocooFroggy** [comment]
Do not check AP Nonce collision. Use preserve data only if you have restored rootfs.

**Comment by masckmaster2007** [comment]
So i did preserve data unfortunately. then i unchecked updated. This is the log:

[theactualgui.log](https://github.com/CoocooFroggy/FutureRestore-GUI/files/7230018/theactualgui.log)

**Comment by Nathanisadumbass** [comment]
what OS you running on your pc

**Comment by CoocooFroggy** [comment]
Try again as an erase restore maybe. You will need to set nonce again. I'm not really sure what went wrong or why. What version of iOS were you on?

**Comment by masckmaster2007** [comment]
@Nathanisadumbass Debian 11. Could try MacOS El Cap. Windows is very unstable.

@CoocooFroggy I was on 14.7.1. Gotta restore to 14.8, set nonce and do the whole setup. Also, there is 2 shsh files when i backup shsh blobs from Conan's TSS Saver. One wich stops with ae and another with cc. Only ae has uncover's nonce![image](https://user-images.githubusercontent.com/63162857/134779802-796c6372-3f6a-41eb-9f87-837700d966d6.jpeg)

**Comment by masckmaster2007** [comment]
Also if i cannot use iOS 14.8 i have shsh blobs for iOS 14.7.1 and 14.6.
As an experiment, i am going to try to restore to iOS 14.7.1 w/ blobs

**Comment by Nathanisadumbass** [comment]
are you using ios 14.8 sep and bb

**Comment by masckmaster2007** [comment]
@Nathanisadumbass yes

Also it seems that everything i do, i get:
ERROR: FDR 0x7f6b6c0011c0 receiving proxy payload failed: Operation now in progress
then after some time fails

**Comment by Nathanisadumbass** [comment]
you should try ubuntu

**Comment by Nathanisadumbass** [comment]
and futurerestore beta

**Comment by masckmaster2007** [comment]
Thanks ! Does live usb work ?

i have Ubuntu 20.04 iso

**Comment by Nathanisadumbass** [comment]
yeah

**Comment by Nathanisadumbass** [comment]
but, how much ram do you have

**Comment by masckmaster2007** [comment]
8gb
Could Ventoy do the job ?

**Comment by masckmaster2007** [comment]
disk where file is located failed. but i still have a recovery disk where i've put Ubuntu. Nice

**Comment by masckmaster2007** [comment]
One reboot later, installed Futurerestore GUI, downloaded BETA binary, and well see...

**Comment by masckmaster2007** [comment]
![Screenshot from 2021-09-25 20-18-28](https://user-images.githubusercontent.com/63162857/134782318-8a131ab6-612c-409f-aae8-a2570f828ac2.png)

**Comment by masckmaster2007** [comment]
![Screenshot from 2021-09-25 20-18-28](https://user-images.githubusercontent.com/63162857/134782353-77791f89-7396-4fd5-baf1-f237291989c9.png)

**Comment by masckmaster2007** [comment]
gonna try release first

**Comment by masckmaster2007** [comment]
Ubuntu said no :|

FDR 0x7fc400001920 Proxy connect request to gg.apple.com:443
FDR 0x7fc400001920 got payload of 517 bytes, now try to proxy it
Sending 517 bytes of data
ERROR: FDR 0x7fc400001920 receiving proxy payload failed: Operation now in progress

**Comment by Nathanisadumbass** [comment]
try https://github.com/m1stadev/futurerestore/actions

**Comment by Nathanisadumbass** [comment]
and use cli

**Comment by masckmaster2007** [comment]
how do i download from github actions ? I am new so i don't know everything

**Comment by masckmaster2007** [comment]
> ### how do i download from github actions ? I am new so i don't know everything
> 
> Well nevermind, found the url: https://pipelines.actions.githubusercontent.com/cRORemcJlbbNOKbf5GvgDpugSe3VuxmGL2smrU2nlCQUYclJtG/_apis/pipelines/1/runs/356/signedartifactscontent?artifactName=futurerestore-linux&urlExpires=2021-09-27T19%3A40%3A14.6436993Z&urlSigningMethod=HMACV1&urlSignature=Mzrp%2FIpT5gMYNkCbWyTYpYYdqspOdo8YoxJg0fLLrHE%3D
> 
> From FCE 365

ETA Answer tomorow

**Comment by masckmaster2007** [comment]
So:

- Use CLI of beta.
- Put device in normal jailbroken mode (which i didn't)
- run under ubuntu.
Hope this works

**Comment by masckmaster2007** [comment]
worked. Thank you very much for the support!!!!!!!!!!!!!!!!! Used iOS 14.8 BB SEP, used Ubuntu with futurerestore in CLI. After many months of trying, i finally reached my goal. Cannot wait for the untethered jailbreak !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by masckmaster2007** [comment]
If you want the command for any reason:

"/path/to/futurerestore" --apticket "/path/to/blob.shsh2" --debug --sep "sep.im4p" --sep-manifest "BuildManifest.plist" --baseband "baseband.Release.bbfw" --baseband-manifest "BuildManifest.plist" "Restore.ipsw"
