### ISSUE TITLE
Icon weird Linux Ubuntu

### ISSUE THREAD

**Issue by olivertzeng** [CoocooFroggy/FutureRestore-GUI#69]
https://user-images.githubusercontent.com/86348833/142848793-979ec30a-2878-4331-9afb-c1890eb087d1.mp4

**Comment by CoocooFroggy** [comment]
Seeing as this happens with blobsaver as well, it's probably just an issue with Java itself. The weird icon is Java's mascot, Duke. I don't think I can do anything about it
