### ISSUE TITLE
what=getting keys failed with error:14745615

### ISSUE THREAD

**Issue by Starlight-D** [CoocooFroggy/FutureRestore-GUI#70]
iphone6s plus is downgraded from 15.1 to 12.0.1 (I only have 12.0.1 shsh), and it appears (what=getting keys failed with error: 14745615 (failed to gei firmwarejson from sever)
are keys pubilcly available?
code=35454993
line=541
file=futurerestore.cpp
commit count=263:
commit sha =50a6375391c94624fbe1b2b060d46117de2bc4fc:
done: restoring failed!
futurerestore process ended.

Ask you, what should I do now? Please help me! Thank you very much!

**Comment by CoocooFroggy** [comment]
So iOS 12 is going to be incompatible with the latest/only signed SEP, 15.1's. I don't think the restore will work, but if you want to try anyway, you can run [wikiproxy](https://github.com/tihmstar/libipatcher/blob/master/wikiproxy.py) or use the latest FutureRestore beta from m1stadev fork (flip the "Download FutureRestore Beta" switch in the GUI) which uses another API for keys.

**Comment by Starlight-D** [comment]
Thank you very much for your reply, which gave me some hope of success, but sorry, I did not find "the latest FutureRestore beta from m1stadev fork" Which version do you mean on Github? I currently use FutureRestore GUI V1.94. In addition, I don’t know how to run wikiproxy (https://github.com/tihmstar/libipatcher/blob/master/wikiproxy.py  ？？) in my MacBook pro2019 （MacOS Monterey 12.0.1）(https://github.com/tihmstar/libipatcher/blob/master/wikiproxy.py) Please continue to help me, thank you very much！

**Comment by CoocooFroggy** [comment]
You can download the latest m1stadev fork FutureRestore beta [from here](https://nightly.link/m1stadev/futurerestore/workflows/ci/test). You can also download it by turning on the "Download FutureRestore Beta" switch in FutureRestore GUI.

If you want to use v194 or tihmstar's FutureRestore, then you can run wikiproxy with python

**Comment by Starlight-D** [comment]
Thank you for your reply. I still can’t make it. Will your program (FutureRestore GUI) add support for downgrading from iOS5.1 to ios12? If you support one day, please let me know, thank you very much 🙏

**Comment by Starlight-D** [comment]
I went to theiphonewiki to find the iOS2.0.1 keys of iPhone6S, but I don’t know how to use them. Please take a moment to add to the downgrade to the server, please 🙏

**Comment by Starlight-D** [comment]
https://www.theiphonewiki.com/wiki/Peace_16A404_(iPhone8,2)

**Comment by CoocooFroggy** [comment]
The downgrade will fail regardless because iOS 15's SEP is not compatible with iOS 12. The lowest you can go to is iOS 14.0 I think.

**Comment by Starlight-D** [comment]
I only have 12.0.1 shsh, so it seems that the only hope is also dashed, thank you for your help!

**Comment by Kovacs19971617** [comment]
> You can download the latest m1stadev fork FutureRestore beta [from here](https://nightly.link/m1stadev/futurerestore/workflows/ci/test). You can also download it by turning on the "Download FutureRestore Beta" switch in FutureRestore GUI.
> 
> If you want to use v194 or tihmstar's FutureRestore, then you can run wikiproxy with python

the page is gone
