### ISSUE TITLE
Which version can I upgrade to?

### ISSUE THREAD

**Issue by lichongjia** [CoocooFroggy/FutureRestore-GUI#72]
hi,buddy！
first,thanks for your project.
my phone is iPhone 6s Plus,im a upgrade/downgrade noob and i have all blobs from 10.3.3 ~ lastest. I don't really understand SEP/BB，but I prefer iOS 12, can I upgrade/downgrade to iOS 12 or any other version?
btw, my current version is 10.3.3.

**Comment by CoocooFroggy** [comment]
Unfortunately you can't, as there's no signed SEP that's compatible for iOS 12. Currently, you can only go to iOS 14 - 15 versions on the 6s+.

**Comment by lichongjia** [comment]
all right, got it. I'll stay on 10.3.3, iOS 14-15 is really laggy and bad for battery life. thanks man.
