### ISSUE TITLE
Cant Innit, No Device Found (Ubuntu 20.04.3)

### ISSUE THREAD

**Issue by GamerToTheMax** [CoocooFroggy/FutureRestore-GUI#73]
Hi So im trying to downgrade my iphone using the beta version however as soon as the device enters dfu/recovery mode the program loses connection and failes and outputs Cant innit no device found. I cannot proceed any further. pls help

**Comment by Heath123** [comment]
Try running futurerestore manually as root, for me it just segfaults but maybe it work for you

**Comment by Heath123** [comment]
Removing `/tmp/firmwares.json` seems to fix it

**Comment by CoocooFroggy** [comment]
This should now be fixed with a FutureRestore beta and #91: FutureRestore GUI v1.98. Downloading the beta will prompt you to run a script as root that should solve the issue.
