### ISSUE TITLE
SEP firmware is NOT being signed! 

### ISSUE THREAD

**Issue by anafinotti** [CoocooFroggy/FutureRestore-GUI#74]
Trying to upgrade iOS 13.3.1 to 14.8 and getting this message.

TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... futurerestore: failed with exception:
[exception]:
what=SEP firmware is NOT being signed!

**Comment by mglebinski** [comment]
The SEP isn't being signed, you cannot downgrade

**Comment by anafinotti** [comment]
I'm trying to upgrade from 13.3.1 to 14.8

**Comment by mglebinski** [comment]
Are you sure the SEP is signed though?

**Comment by mglebinski** [comment]
Not afaik, the sep has to be signed to allow you to do so

**Comment by CoocooFroggy** [comment]
This was probably due to using futurerestore-v194 instead of the beta which can parse iOS 15 SEP & BB.
