### ISSUE TITLE
A14 support just released!

### ISSUE THREAD

**Issue by iD7me** [CoocooFroggy/FutureRestore-GUI#78]
Cryptiiiic just released new version that support A14 device restore on iOS 15
Would you please add it to your tool?
https://twitter.com/Cryptiiiic/status/1499192035525357574

**Comment by jojobrogess** [comment]
https://github.com/m1stadev/futurerestore/tree/test

**Comment by CoocooFroggy** [comment]
Completed in #79. Thanks for the issue
