### ISSUE TITLE
Can't restore iphone 6s plus 15.3 to 15.2 beta 1

### ISSUE THREAD

**Issue by HuyNguyenGia-3103** [CoocooFroggy/FutureRestore-GUI#81]
i tried to downgrade from 15.3 to 15.2 b1, IP 6s Plus, Samsung chip N66AP, shsh from shsh.host (auto save), ipsw from ipsw.dev. It say in picture. When i use img4tool, my Shsh have good generator and i have set nonce to my device 0x1111111111111111, the shsh have generator = 0x11.., too, but it didn’t work. I tried with lastest release of future restore gui, but it has the same error. If i use recovery mode -> apnonce mismatch error. If use PwnDfu -> no generator error. I sure my nonce on iphone and shsh blob is true.

**Comment by CoocooFroggy** [comment]
Check what AP Nonce is in the blob, and then go into recovery mode and check the AP Nonce there. They most likely do not match, meaning either the blob's generator is lying or your phone's generator was not set correctly.
