### ISSUE TITLE
Can I use the Futurerestore GUI to upgrade to 15.1?

### ISSUE THREAD

**Issue by execOQ** [CoocooFroggy/FutureRestore-GUI#89]

**Comment by CoocooFroggy** [comment]
You can! You'll need to use macOS or Linux. Make sure to check "FutureRestore Beta" in settings and download FutureRestore again. Also be sure to use the "Custom Latest" option to specify 15.3.1 firmware with Latest Baseband and Latest SEP.

**Comment by execOQ** [comment]
Thanks! Can I use Windows?

**Comment by CoocooFroggy** [comment]
FutureRestore itself doesn't support Windows & iOS 15, so you won't be able to download FutureRestore Beta on Windows.

**Comment by execOQ** [comment]
oh... i got it, thanks again)
