### ISSUE TITLE
Add support for new FutureRestore version V274

### ISSUE THREAD

**Issue by iD7me** [CoocooFroggy/FutureRestore-GUI#90]
I don't know if you really need to add support of this 
https://twitter.com/Cryptiiiic/status/1506481763840782345

So we can use it with 15.3RC because Cryptic said we can't follow the same way we did it before 
Thank you.

**Comment by CoocooFroggy** [comment]
Added in #91: FutureRestore GUI — v1.98
It's prerelease right now because I would like to get rid of the window resizing issue first.

**Comment by iD7me** [comment]
> Added in #91: FutureRestore GUI — v1.98
> 
> It's prerelease right now because I would like to get rid of the window resizing issue first.

Is it okay to use 1.98 version? Or should use the latest one 1.97.2?

**Comment by CoocooFroggy** [comment]
You can definitely use 1.98, get it in the [releases tab](https://github.com/CoocooFroggy/FutureRestore-GUI/releases). If you try to shrink the window it may glitch a bit, but that's the only issue. Other than that, it should be good to go!
