### ISSUE TITLE
SLF4J Error

### ISSUE THREAD

**Issue by ricefieldw** [CoocooFroggy/FutureRestore-GUI#99]
I'm not really sure what the error is but everytime I click start it shows this error and opens 2 more windows of futurerestore. 
![Screenshot 2022-07-18 154726](https://user-images.githubusercontent.com/109187677/179629912-8a9e3e05-157e-42b0-8f63-92e58e04b47a.png)

iPhone 11 Pro, iOS 15.5 to 15.1

**Comment by CoocooFroggy** [comment]
You've selected FutureRestore **GUI** as the binary. You need to select a downloaded FutureRestore from [here](https://github.com/futurerestore/futurerestore/actions), or download it from within FRGUI.
